project_name: my_vint
run_name: vint
load_run: "my_vint/vint_2025_03_13_15_57_16"
run_id: "8aodddq1"

# training setup
method: "BC" # BC or GOAL
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 256
epochs: 100
gpu_ids: [0]
num_workers: 2
lr: 5e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 0
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: vint
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# distance bounds for distance and action and distance predictions 
action:
  min_dist_cat: 0
  max_dist_cat: 10
close_far_threshold: 10 # distance threshold used to seperate the close and the far subgoals that are sampled per datapoint

# action output params
len_traj_pred: 3

# dataset specific parameters
image_size: [224, 128] # width, height
obs_type: "image"
goal_type: "image"

datasets:
  # seattle:
  #   data_folder: /home/<username>/vint_dataset/seattle/
  #   train: /home/<username>/data_splits/seattle/train/
  #   test: /home/<username>/data_splits/seattle/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

  scand:
    data_folder: /home/yzc/CRUEL/ourdata
    train: /home/yzc/CRUEL/ourdata_splits/train/ #data_splits_folder
    test: /home/yzc/CRUEL/ourdata_splits/test/ #data_splits_folder
    end_slack: 0
    goals_per_obs: 3
    negative_mining: False

# logging stuff
## =0 turns off
print_log_freq: 1 # in iterations
image_log_freq: 4 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 2 # in iterations
eval_freq: 1 # in epochs