project_name: my_vint
run_name: vint
# load_run: "my_vint/vint_2025_04_07_15_03_44"
# run_id: "kw368kn2"

# training setup
method: "base" # base or cnnaux or tokenaux
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 128
epochs: 50
gpu_ids: [0]
num_workers: 8
lr: 5e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 0
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: vint
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# action output params
len_traj_pred: 2

# dataset specific parameters
image_size: [224, 128] # width, height
obs_type: "image"
goal_type: "image"

datasets:
  debugdata:
    data_folder: /home/yzc/CRUEL/debugdata
    train: /home/yzc/CRUEL/debugdata_splits/train/
    test: /home/yzc/CRUEL/debugdata_splits/test/

  ourdata:
    data_folder: /home/yzc/CRUEL/ourdata
    train: /home/yzc/CRUEL/ourdata_splits/train/ #data_splits_folder
    test: /home/yzc/CRUEL/ourdata_splits/test/ #data_splits_folder
    # data_folder: /Users/pollux/Documents/Robot_Navigation/CRUEL/ourdata
    # train: /Users/pollux/Documents/Robot_Navigation/CRUEL/ourdata_splits/train/ #data_splits_folder
    # test: /Users/pollux/Documents/Robot_Navigation/CRUEL/ourdata_splits/test/ #data_splits_folder

# logging stuff
## =0 turns off
print_log_freq: 5 # in iterations
image_log_freq: 8 # in iterations
num_images_log: 6 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 5 # in iterations
eval_freq: 1 # in epochs