project_name: my_vint
run_name: vint
# load_run: "my_vint/vint_2025_04_09_00_47_49"
# run_id: "28bzh5w3"

# training setup
gpu_id: 0
method: "gazetoken" # base or cnnaux or gazeaux or personaux or gazechannel or personchannel or gazetoken or persontoken or sel
use_wandb: True # set to false if you don't want to log to wandb
wandb_log_freq: 110 # in iterations
train: True
batch_size: 128
epochs: 200
num_workers: 8
lr: 5e-4
optimizer: adamw
clipping: True
max_norm: 1.
scheduler: "cosine"
warmup: True  
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# Early stopping parameters
early_stopping: true  # 是否启用早停
patience: 200         # 容忍多少个epoch测试损失没有改善
min_delta: 0.0001    # 改善阈值

# Stage training parameters (only used when method is "sel")
stage1_epochs: 50
stage2_epochs: 30
stage3_epochs: 50
stage1_loss_threshold: 0.1
stage2_loss_threshold: 0.1
stage3_loss_threshold: 0.1

# model params
model_type: vint
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# action output params
len_traj_pred: 2

# dataset specific parameters
image_size: [160, 128] # width, height
obs_type: "image"
goal_type: "image"

datasets:
  debugdata:
    data_folder: /home/yzc/CRUEL/debugdata
    train: /home/yzc/CRUEL/debugdata_splits/train/
    test: /home/yzc/CRUEL/debugdata_splits/test/

  data:
    data_folder: /home/yzc/CRUEL/data
    train: /home/yzc/CRUEL/data_splits/train/ #data_splits_folder
    test: /home/yzc/CRUEL/data_splits/test/ #data_splits_folder
    # data_folder: /Users/pollux/Documents/Robot_Navigation/CRUEL/data
    # train: /Users/pollux/Documents/Robot_Navigation/CRUEL/data_splits/train/ #data_splits_folder
    # test: /Users/pollux/Documents/Robot_Navigation/CRUEL/data_splits/test/ #data_splits_folder

# logging stuff
## =0 turns off
print_log_freq: 220 # in iterations
image_log_freq: 220 # in iterations
num_images_log: 6 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
eval_freq: 1 # in epochs